name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install tmux
        run: sudo apt-get update && sudo apt-get install -y tmux

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Make test scripts executable
        run: chmod +x ./tests/run_test.sh ./tests/clean_up.sh

      - name: Run Robot Framework Tests
        run: ./tests/run_test.sh
